<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.49">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Marcelo Ortiz, Universitat Pompeu Fabra">
<meta name="dcterms.date" content="2024-01-01">

<title>Contract Theory and Accounting</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script>window.backupDefine = window.define; window.define = undefined;</script><script src="https://cdn.jsdelivr.net/npm/katex@latest/dist/katex.min.js"></script>
  <script>document.addEventListener("DOMContentLoaded", function () {
 var mathElements = document.getElementsByClassName("math");
 var macros = [];
 for (var i = 0; i < mathElements.length; i++) {
  var texText = mathElements[i].firstChild;
  if (mathElements[i].tagName == "SPAN") {
   katex.render(texText.data, mathElements[i], {
    displayMode: mathElements[i].classList.contains('display'),
    throwOnError: false,
    macros: macros,
    fleqn: false
   });
}}});
  </script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script><link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@latest/dist/katex.min.css">

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="floating">

<div id="quarto-search-results"></div>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <nav id="TOC" role="doc-toc" class="toc-active" data-toc-expanded="99">
    <h2 id="toc-title">On this page</h2>
   
  <ul class="collapse">
  <li><a href="#introduction-to-moral-hazard" id="toc-introduction-to-moral-hazard" class="nav-link active" data-scroll-target="#introduction-to-moral-hazard">Introduction to Moral Hazard</a>
  <ul class="collapse">
  <li><a href="#a-very-simple-example" id="toc-a-very-simple-example" class="nav-link" data-scroll-target="#a-very-simple-example">A Very Simple Example</a></li>
  </ul></li>
  <li><a href="#general-model-of-moral-hazard" id="toc-general-model-of-moral-hazard" class="nav-link" data-scroll-target="#general-model-of-moral-hazard">General Model of Moral Hazard</a>
  <ul class="collapse">
  <li><a href="#first-order-simplification" id="toc-first-order-simplification" class="nav-link" data-scroll-target="#first-order-simplification">First-Order Simplification</a></li>
  <li><a href="#solving-optimal-contract" id="toc-solving-optimal-contract" class="nav-link" data-scroll-target="#solving-optimal-contract">Solving optimal contract</a></li>
  <li><a href="#accounting-performance-measures" id="toc-accounting-performance-measures" class="nav-link" data-scroll-target="#accounting-performance-measures">Accounting Performance Measures</a></li>
  </ul></li>
  <li><a href="#linear-exponential-normal-len-models" id="toc-linear-exponential-normal-len-models" class="nav-link" data-scroll-target="#linear-exponential-normal-len-models">Linear-exponential-normal (LEN) models</a>
  <ul class="collapse">
  <li><a href="#solving-optimal-contract-1" id="toc-solving-optimal-contract-1" class="nav-link" data-scroll-target="#solving-optimal-contract-1">Solving optimal contract</a></li>
  <li><a href="#accounting-perfomance-measures" id="toc-accounting-perfomance-measures" class="nav-link" data-scroll-target="#accounting-perfomance-measures">Accounting Perfomance Measures</a></li>
  <li><a href="#optimal-contract-with-performance-measures" id="toc-optimal-contract-with-performance-measures" class="nav-link" data-scroll-target="#optimal-contract-with-performance-measures">Optimal contract with Performance Measures</a></li>
  <li><a href="#recent-papers-in-accounting" id="toc-recent-papers-in-accounting" class="nav-link" data-scroll-target="#recent-papers-in-accounting">Recent papers in Accounting</a></li>
  </ul></li>
  <li><a href="#multiple-action-models" id="toc-multiple-action-models" class="nav-link" data-scroll-target="#multiple-action-models">Multiple-action models</a></li>
  <li><a href="#disclosure-of-private-information" id="toc-disclosure-of-private-information" class="nav-link" data-scroll-target="#disclosure-of-private-information">Disclosure of Private information</a></li>
  </ul>
</nav>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar zindex-bottom">
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Contract Theory and Accounting</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Marcelo Ortiz, Universitat Pompeu Fabra </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">January 1, 2024</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="introduction-to-moral-hazard" class="level1">
<h1>Introduction to Moral Hazard</h1>
<p>Moral hazard arises when the value of a transaction for one party can be influenced by actions or decisions taken by the other party. Two additional conditions are required for the problem of moral hazard to occur:</p>
<ul>
<li>Hidden action: This action is not directly observable or perfectly inferable by the party whose results are affected.</li>
<li>Risk aversion: At least one of the parties must be risk-averse.</li>
</ul>
<p>The essence of the moral hazard problem lies in the conflict between two fundamental objectives:</p>
<ul>
<li>Provision of adequate incentives.</li>
<li>Efficient risk distribution.</li>
</ul>
<p>There is a substitution effect: the extent to which one party is shielded from risk influences their incentives to take actions that are efficient for the other party.</p>
<p>The challenge is to design an compensation scheme or incentive mechanism that minimizes the conflict between the two objectives. The optimal solution depends on the characteristics of the parties involved, such as their risk aversion, the observability of their actions, and the nature of the relationship between them.</p>
<section id="a-very-simple-example" class="level2">
<h2 class="anchored" data-anchor-id="a-very-simple-example">A Very Simple Example</h2>
<p>Let’s assume that a company (principal) hires a manager (agent) responsible for running the business. The company’s outcomes depend on both random factors and the manager’s effort. For now, let’s assume the effort can be either high (A) or low (B), and the company’s outcomes can either be success (E) or failure (F). The company’s profit in the success scenario is $360, and in the failure scenario, it is $200. The probability of success is 75% with high effort and 25% with low effort.</p>
<p>Therefore, the expected profit of the principal when effort is high is: <span class="math inline">360 \times 0.75 + 200 \times 0.25 = 320</span>. In contrast, when the effort is low the expected profit is: <span class="math inline">360 \times 0.25 + 200 \times 0.75 = 240</span>.</p>
<p>This can be summarized in the following table:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th></th>
<th>High Effort (A)</th>
<th>Low Effort (B)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Success (S)</td>
<td>75%</td>
<td>25%</td>
</tr>
<tr class="even">
<td>Failure (F)</td>
<td>25%</td>
<td>75%</td>
</tr>
<tr class="odd">
<td>Expected Profit</td>
<td>$320</td>
<td>$240</td>
</tr>
</tbody>
</table>
<p>We assume that the principal seeks to maximize the expected value of their net profits (expected value minus the payment to the agent). For now, let’s consider the principal to be risk-neutral.</p>
<p>The agent (manager) aims to maximize an expected utility function of the form:</p>
<p><span class="math display">
U = U(w) - v(e)
</span></p>
<p>Where <span class="math inline">U(w)</span> is the utility of the payment received (remuneration), and <span class="math inline">v(e)</span> is the cost of effort <span class="math inline">e</span>.</p>
<p>We can distinguish four possible cases:</p>
<ol type="1">
<li>Observable effort, risk-neutral agent</li>
<li>Non-observable effort, risk-neutral agent</li>
<li>Observable effort, risk-averse agent</li>
<li>Non-observable effort, risk-averse agent</li>
</ol>
<section id="observable-effort-risk-neutral-agent" class="level3">
<h3 class="anchored" data-anchor-id="observable-effort-risk-neutral-agent">Observable Effort, Risk-Neutral Agent</h3>
<p>Let’s assume an agent with a utility function <span class="math inline">U = w - v(e)</span>, and a reservation utility of <span class="math inline">\underline{U} = 81</span>. The costs of effort are <span class="math inline">v(B) = 0</span> and <span class="math inline">v(A) = 63</span>. (The numbers are arbitrary and chosen to facilitate later comparisons).</p>
<p>If the principal settles for low effort, they offer the agent a salary equal to the reservation utility <span class="math inline">w = 81</span>. The expected profit for the principal is 240, and the net benefit is <span class="math inline">240 - 81 = 159</span>.</p>
<p>If the principal wants to ensure high effort, the agent’s remuneration must cover the disutility of effort, i.e., <span class="math inline">w = 81 + 63 = 144</span>. The net profit for the principal in this case is <span class="math inline">320 - 144 = 176</span>.</p>
<p>Thus, for the principal, the best alternative is to offer a fixed payment of 144 and obtain an expected profit of 176.</p>
</section>
<section id="non-observable-effort-risk-neutral-agent" class="level3">
<h3 class="anchored" data-anchor-id="non-observable-effort-risk-neutral-agent">Non-Observable Effort, Risk-Neutral Agent</h3>
<p>Now, consider the case where the effort (A or B) is non-observable and the agent continue being risk-neutral. In this case, the conflict between incentives and risk distribution is easily resolved. The most effective way to provide incentives is to make the agent bear all the consequences of their decisions.</p>
<p>The contract cannot depend on effort because effort is neither observable nor verifiable. However, results such as profits are observable. Therefore, the principal can exploit the correlation between effort and profits to incentivize the agent. The principal will pay <span class="math inline">X</span> in case of success ($E$), and <span class="math inline">Y</span> in case of failure (<span class="math inline">F</span>). This introduces uncertainty for the agent.</p>
<p>The principal can induce high effort by offering the agent a contract characterized by a compensation conditional on the outcome: <span class="math inline">W_E</span> and <span class="math inline">W_F</span>, with the following requirements:</p>
<ol type="1">
<li><strong>Individual Rationality</strong>: The utility for the agent must be greater than their reservation utility.</li>
<li><strong>Incentive Compatibility</strong>: The utility of exerting high effort must be greater than the utility of low effort, i.e.,<span class="math inline">E[U(A)] &gt; E[U(B)]</span>.</li>
</ol>
<p>In our example, the constraints are:</p>
<p><span class="math display">
0.75 W_E + 0.25 W_F - 63 \geq 81
</span> <span class="math display">
0.75 W_E + 0.25 W_F - 63 \geq 0.25 W_E + 0.75 W_F
</span></p>
<p>As it is inefficient for the principal to pay more than needed to influence effort, the previous system of inequations are solved at the equality conditions. The optimal contract in this case involves:</p>
<p><span class="math display">
W_E = 184, \quad W_F = 24.
</span></p>
</section>
<section id="observable-effort-risk-averse-agent" class="level3">
<h3 class="anchored" data-anchor-id="observable-effort-risk-averse-agent">Observable Effort, Risk-Averse Agent</h3>
<p>Qhat happens when we have a risk-averse agent? For example, assume the utility function <span class="math inline">U = W^{1/2} - v(e)</span>, where <span class="math inline">v(A) = 3</span> and <span class="math inline">v(B) = 0</span>, and the reservation utility is <span class="math inline">\underline{U} = 9</span>.</p>
<p>To induce low effort, it is sufficient to offer a fixed salary that yields a utility level equal to or greater than the reservation utility (<span class="math inline">W=\underline{U}^2=81</span>). The principal’s expected net profit is <span class="math inline">240 - 81 = 159</span>, the same as in the scenario with a risk-neutral agent.</p>
<p>To induce high effort, the agent needs to be compensated for the additional disutility of the high effort. As effort can be observed, this can be achieved with a fixed salary of <span class="math inline">144=(\underline{U}+3)^2</span>, conditioned on high effort . Thus, the expected net profit for the principal is <span class="math inline">320 - 144 = 176</span>, higher than the profit for low effort (though it may not always be optimal to pay for high effort).</p>
<p>In this case, the agent’s risk aversion does not pose a problem since there is no uncertainty involved. The agent’s action and payment are not contingent on the state of nature.<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a></p>
</section>
<section id="non-observable-effort-and-risk-averse-agent" class="level3">
<h3 class="anchored" data-anchor-id="non-observable-effort-and-risk-averse-agent">Non-Observable Effort and Risk-Averse Agent</h3>
<p>The lack of observability of effort forces to create the compensation contract contingent on outcomes (which are correlated with effort) or abandoning variable compensation altogether. In this scenario we can see the main conflict in moral hazard problems:</p>
<ul>
<li><p><strong>Efficient Risk Distribution</strong>: the risk-neutral party (the principal) should bear all the risk, while the risk-averse party (the agent) remains on the certainty line.</p></li>
<li><p><strong>Incentive Problem</strong>: For proper incentives, the agent must perceive differences in remuneration based on their effort level.</p></li>
</ul>
<p>The challenge is to find the optimal balance between incentive provision and risk distribution. In the case of a risk-neutral agent, this was not a significant issue, as simply transferring residual control to the agent solved the problem. However, in this case, any variable compensation scheme must compensate the risk-averse agent for the risk they bear.</p>
<p>For comparison, let’s keep the utility function and parameters from the previous section. If the principal desires low effort, a fixed salary of <span class="math inline">81</span> is sufficient. However, to incentive high effort, the contract with <span class="math inline">w = 144</span> will no longer suffice because effort is not observable, and uniform wages provide an incentive to cheat by exerting low effort.</p>
<p>The contract that induces high effort must meet both the individual rationality and incentive compatibility constraints, expressed as:</p>
<p><span class="math display">
0.75U(W_E) + 0.25U(W_F) - 3 \geq 9
</span></p>
<p><span class="math display">
0.75U(W_E) + 0.25U(W_F) - 3 \geq 0.25U(W_E) + 0.75U(W_F)
</span></p>
<p>The second constraint can be written as <span class="math inline">0.5[U(W_E) - U(W_F)] \geq 3</span>. This captures the difference in utilities associated with the remuneration in each state, ensuring that high effort is chosen over low effort. The solution for this system of equation is <span class="math inline">W_E = 182.25</span> and <span class="math inline">W_F = 56.25</span>. The expected cost of the contract that incentives high effor for the principal is <span class="math inline">0.75 \times 182.25 + 0.25 \times 56.25 = 159.75</span>, leaving them with an expected net benefit of <span class="math inline">320 - 159.75 = 169.25</span>.</p>
<p>It is important to note that inducing high effort now has a higher cost for the principal compared to the observable effort case. The cost has increased from <span class="math inline">144</span> to <span class="math inline">159.75</span>. The additional <span class="math inline">6.75</span> is the cost of non-observability, which economically corresponds to compensating the agent for the risk assumed.</p>
</section>
</section>
</section>
<section id="general-model-of-moral-hazard" class="level1">
<h1>General Model of Moral Hazard</h1>
<p>This section borrows from <span class="citation" data-cites="Lambert_2001">Lambert (<a href="#ref-Lambert_2001" role="doc-biblioref">2001</a>)</span> Chapter 2 and <span class="citation" data-cites="Bolton_Dewatripont_2005">Bolton and Dewatripont (<a href="#ref-Bolton_Dewatripont_2005" role="doc-biblioref">2005</a>)</span> Chapter 4. Here we develop more general version of the moral hazard problem. We start by stating the more general framework, and then applying for specific functional forms for the level of effort and performance outcome.</p>
<p>Moral hazard problems can be modeled as sequential games where, in the first stage, the principal offers a contract, and in the second stage, the agent must accept or reject it and then choose their level of effort. Thus, it is a problem that can be solved using backward induction.</p>
<p>In the final stage of the game, the agent chooses a level of effort considering the <span class="math inline">n</span> potential performance outcomes.</p>
<p><span class="math display">
e \in \max \sum_{i=1}^n p_i(e)U(w(x_i)) - v(e)
</span></p>
<p>This condition corresponds to the incentive compatibility constraint. In the immediately preceding stage, the agent decides whether to participate in the contract:</p>
<p><span class="math display">
\sum_{i=1}^n p_i(e)U(w(x_i)) - v(e) \geq \underline{U}
</span></p>
<p>This corresponds to the participation constraint.</p>
<p>In the first stage of the problem, the principal designs the contract , anticipating the agent’s behavior. Formally, the contract proposed by the principal is the solution to:</p>
<p><span class="math display">
\max \sum_{i=1}^n p_i(e)[B(x_i - w(x_i))]
</span></p>
<p>Subject to:</p>
<p><span class="math display">
\underline{U} \leq \sum_{i=1}^n p_i(e)U(w(x_i)) - v(e)
</span></p>
<p><span id="eq-agent_problem"><span class="math display">
e \in \max \sum_{i=1}^n p_i(e)U(w(x_i)) - v(e)
\tag{1}</span></span></p>
<section id="first-order-simplification" class="level2">
<h2 class="anchored" data-anchor-id="first-order-simplification">First-Order Simplification</h2>
<p>The constraint in <a href="#eq-agent_problem" class="quarto-xref">Equation&nbsp;1</a> is not very tractable, and theorist have develop conditions where it can be replaced by the agent’s first-order condition on effort. If we assume that the agent’s optimal effort is in the interior of the effort set, then the agent first-order condition is</p>
<p><span class="math display">
\sum_{i=1}^n p_i'(e)U(w(x_i)) - v'(e)=0
</span></p>
<p>The issue with this method is that the first-order condition is necessary but not sufficient. Effort is present in both the disutility function <span class="math inline">v(e)</span> and the probability distribution of results, implying that the expected utility function is not necessarily concave. Therefore, the first-order approach may yield more solutions than the original problem, potentially leading to suboptimal outcomes for the principal. We must impose restrictions on the conditional distribution of outcomes given effort to ensure that the second-order condition holds.</p>
</section>
<section id="solving-optimal-contract" class="level2">
<h2 class="anchored" data-anchor-id="solving-optimal-contract">Solving optimal contract</h2>
<p>The Lagrangian for the principal’s problem using the first-condition approach is:</p>
<p><span class="math display">
L(w(x),e) = \sum_{i=1}^n p_i(e)[B(x_i - w(x_i))]+ \lambda \left[ \sum_{i=1}^n p_i(e)U(w(x_i)) - v(e) -\underline{U}  \right] + \mu \left[\sum_{i=1}^n p_i'(e)U(w(x_i)) - v'(e)\right]
</span></p>
<p>we can characterize the optimal contract by deriving the Lagrangian with respect to <span class="math inline">w</span> for each value of <span class="math inline">x</span>. This contract must satisfy that</p>
<p><span id="eq-op_sharing"><span class="math display">
\frac{B'(x_i - w(x_i))}{U'(w(x_i)) }= \lambda + \mu \frac{p_i'(e)}{p_i(e)}
\tag{2}</span></span></p>
<p>So, <span class="math inline">\mu=0</span> reduces the optimal contract to the first-best solution. <span class="citation" data-cites="Holmstrom_1979">Holmström (<a href="#ref-Holmstrom_1979" role="doc-biblioref">1979</a>)</span> shows that as long as the principal aims to influence more effort than the lowest possible, then <span class="math inline">\mu&gt;0</span>. In those cases, the optimal risk sharing depends on the sign and magnitude of <span class="math inline">\frac{p_i'(e)}{p_i(e)}</span>. An statistical interpretation of this ratio is that the principal use the outcome <span class="math inline">x</span> to infer the parameter <span class="math inline">e</span>, that is, the effort level taken <span class="citation" data-cites="Milgrom_1981">(<a href="#ref-Milgrom_1981" role="doc-biblioref">Milgrom 1981</a>)</span>. In other words, the principal rewards the outcomes that are more likely to happen with higher level of efforts (<span class="math inline">p_i'(e)&gt;0</span>).</p>
<p><a href="#eq-op_sharing" class="quarto-xref">Equation&nbsp;2</a> indicates that the optimal contract shape depends on the functional form for the principal’s and agent’s utility functions as well as for outcome distribution function. Depending on these settings, the optimal contract can be linear, convex, or concave in <span class="math inline">x</span>. A sufficient condition for the contract to be monotonically increasing in the outcome is that <span class="math inline">\frac{p_i'(e)}{p_i(e)}</span>is increasing in the outcome (called <strong>monotone likelihood ratio condition</strong>, MLRC ), which is a stronger condition the the mean of the outcome distribution to increase with the outcome. This condition is meet by many common probability functions.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Linearity in the Outcome
</div>
</div>
<div class="callout-body-container callout-body">
<p>Even if the likelihood ratio is monotonic and linear in the outcome, this would not imply that the optimal compensation is also linear in the outcome. As <a href="#eq-op_sharing" class="quarto-xref">Equation&nbsp;2</a> shows, the shape of the contract also depends on the preference functions of the agent and the principal.</p>
</div>
</div>
<p>For example, assuming the the principal is risk neutral and the agent’s has an hyperbolic absolute risk aversion (HARA) utility function, then the optimal compensation is a concave function of the outcome, as shown in <a href="#eq-hara" class="quarto-xref">Equation&nbsp;3</a>.</p>
<p><span id="eq-hara"><span class="math display">
\begin{align*}
U(x) &amp;=\frac{1}{1-\gamma}\left(\delta_0+\delta_1 x\right)^(1-\gamma)\\
w^*(x) &amp;= -\frac{ \delta_0}{ \delta_1 x} + \delta_1^{(1-\gamma)/\gamma} \left[ \lambda + \mu \frac{p_i'(e)}{p_i(e)} \right]^{1/\gamma}
\end{align*}
\tag{3}</span></span></p>
<p>Thus, the optimal contract is linear in the outcome if <span class="math inline">\gamma=1</span> (e.g., logarithmic utility function), and concave (convex) if <span class="math inline">\gamma&gt;1</span> (<span class="math inline">\gamma&lt;1</span>).</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Limited Liability
</div>
</div>
<div class="callout-body-container callout-body">
<p>In many instances, the optimal compensation needs to be bounded below given limited liability or wealth constraints of the agent. The problem is that <a href="#eq-op_sharing" class="quarto-xref">Equation&nbsp;2</a> implies penalization to the agent for bad outcomes. Therefore, the optimal compensation is often nondifferentiable and has a piecewise linear form. See <span class="citation" data-cites="Mirrlees_1974">Mirrlees (<a href="#ref-Mirrlees_1974" role="doc-biblioref">1974</a>)</span>.</p>
</div>
</div>
</section>
<section id="accounting-performance-measures" class="level2">
<h2 class="anchored" data-anchor-id="accounting-performance-measures">Accounting Performance Measures</h2>
<p>Now let’s add an additional performance measure to the model to check in which conditions they reduced the welfare loss relative to the first-best solution. This will be the case if they increase the agent’s incentive to exert effort or improve the risk-sharing between the principal and the agent. Be <span class="math inline">y</span> the performance measure. In this case, <a href="#eq-op_sharing" class="quarto-xref">Equation&nbsp;2</a> becomes</p>
<p><span id="eq-op_sharing_2"><span class="math display">
\frac{B'(x_i - w(x_i,y_i))}{U'(w(x_i,y_i)) }= \lambda + \mu \frac{p_i'(x,y;e)}{p_i(x,y;e)}
\tag{4}</span></span></p>
<p>Thus, the optimal contract depends on the performance metric if <span class="math inline">\frac{p_i'(x,y;e)}{p_i(x,y;e)}</span> also depends on <span class="math inline">y</span>. However, if <span class="math inline">x</span> is a sufficient statistic for <span class="math inline">x</span> and <span class="math inline">y</span> with respect to <span class="math inline">e</span>, then the optimal contract is independent of <span class="math inline">y</span>. This is called Holmstrom’s informativeness condition <span class="citation" data-cites="Holmstrom_1979">(<a href="#ref-Holmstrom_1979" role="doc-biblioref">Holmström 1979</a>)</span>.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Sufficient Statistic
</div>
</div>
<div class="callout-body-container callout-body">
<p>If <span class="math inline">x=e+a_1</span> and <span class="math inline">y=x+a_2</span>, where <span class="math inline">a_1</span> and <span class="math inline">a_2</span> are independent random variables, then <span class="math inline">x</span> is a <strong>sufficient statistic</strong> for <span class="math inline">x</span> and <span class="math inline">y</span> with respect to <span class="math inline">e</span>. In other words, <span class="math inline">y</span> does not add any information about <span class="math inline">e</span> that is not already contained in <span class="math inline">x</span>.</p>
</div>
</div>
<p>Accounting systems aggregate performance measures. The demand for aggregation of performance measures arises because reporting all the basic transactions and other nonfinancial information is costly and unrealistic. Accountants aggregate linearly these measures assigning equal weights to each them. For example, total cost is the sum of each cost item, net benefits is revenues minus expenses. Furthermore, in practice, performance evaluation and compensation usually rely on those accounting aggregated metrics. To what extent contract theory support the linear aggregation of performance with equal weights? <span class="citation" data-cites="Banker_1989">Banker and Datar (<a href="#ref-Banker_1989" role="doc-biblioref">1989</a>)</span> provide theoretical support for the linear aggregation but also highlight that the equal weights assumption is rarely optimal. The components of the performance measure should be weighted according to agent’s capacity to influence them and their noisiness. Thus, only in cases where the signal-to-noise ratio is the same for all components, the equal weights assumption might be optimal. To see this, let’s continue with the same example but now assume that the principal is risk neutral and that <span class="math inline">x</span> and <span class="math inline">y</span> are both performance metrics. The optimal contract is given by <a href="#eq-op_sharing_2" class="quarto-xref">Equation&nbsp;4</a> and yields</p>
<p><span class="math display">
w^*(x,y)= W \left[ \lambda + \mu \frac{p_i'(x,y;e)}{p_i(x,y;e)} \right]
</span></p>
<p>where <span class="math inline">W</span> is the inverse of the agent’s marginal utility function. Let’s define the aggregate performance measure as <span class="math inline">\pi(x,y)=\lambda + \mu \frac{p_i'(x,y;e)}{p_i(x,y;e)}</span>. For many probability distributions, such as those in the exponential family, the likelihood ratio is linear in <span class="math inline">x</span> and <span class="math inline">y</span>, thus the optimal contract supports linear aggregation. In terms of the optimal weights, <span class="citation" data-cites="Banker_1989">Banker and Datar (<a href="#ref-Banker_1989" role="doc-biblioref">1989</a>)</span> shows that for the exponential family of distribution, when both metrics are independently distributed given the agent’s effort, then the optimal weights are proportional to (1) the sensitivity of the metric to the effort, and (2) to the inverse of the variance of the performance metrics. If we denote the weights as <span class="math inline">\beta_x</span> and <span class="math inline">\beta_y</span>, then the optimal weights are given by</p>
<p><span class="math display">
\beta_x  = \frac{\frac{\partial E(x;e)}{ \partial e} var(y) }{ \left[ var(x)+var(y) \right]}
</span></p>
<p>and <span class="math display">
\beta_y  = \frac{\frac{\partial E(y;e)}{ \partial e} var(x) }{ \left[ var(x)+var(y) \right]}
</span></p>
<p>and the relative weights are</p>
<p><span id="eq-optimal_weights"><span class="math display">
\frac{\beta_x}{\beta_y} = \frac{\partial E(x;e)/ \partial e}{var(x)} \frac{var(y)}{\partial E(y;e)/ \partial e}
\tag{5}</span></span></p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
The relevance of variables not controlled by the agent
</div>
</div>
<div class="callout-body-container callout-body">
<p>If the principal or other agent invest in technology or capital such as the agent’s effort is more productive or the performance metric is more sensitive to its effort, then it is optimal to introduce those variables into the contract even though are not controlled by the agent. In this case, the optimal contract adjusts the compensation to subtract the principal’s investment effect on the mean outcome or adjusts the weights of the performance metrics to reflect their new informativeness.</p>
</div>
</div>
<p>How the optimal contract should weights performance metrics that are correlated? In that case, <a href="#eq-optimal_weights" class="quarto-xref">Equation&nbsp;5</a> is rewritten as</p>
<p><span id="eq-optimal_weights_2"><span class="math display">
\frac{\beta_x}{\beta_y} = \frac{ \frac{\partial E(x;e)}{\partial e} - \frac{cov(x,y)}{var(y)}\frac{\partial E(y;e)}{\partial e} }{var(x)} \frac{var(y)}{\frac{\partial E(y;e)}{\partial e} - \frac{cov(x,y)}{var(x)}\frac{\partial E(x;e)}{\partial e}}
\tag{6}</span></span></p>
<p>so, even if the agent does not control <span class="math inline">y</span> (e.g., <span class="math inline">\frac{\partial E(y;e)}{\partial e}=0</span>) then both metrics should be included in the contract with weights that reflect the correlation between them.</p>
<p><span class="math display">
\frac{\beta_x}{\beta_y} = -\frac{var(y)}{covar(x,y)}
</span></p>
<p>Thus, if the metrics are positively correlated, then their weights have opposite signs. The interpretation is that the positive correlation is driven by an exogenous common factor, and by adjusting <span class="math inline">y</span> with a negative weight some of the noise driven by the common factor in <span class="math inline">x</span> is removed.</p>
</section>
</section>
<section id="linear-exponential-normal-len-models" class="level1">
<h1>Linear-exponential-normal (LEN) models</h1>
<p>Now we develop another widely used model considering linear contracts, normally distributed performance and exponential utility for the agent. The performance outcome is assumed to be equal to effort (in monetary terms) plus noise: <span class="math inline">x=e+\epsilon</span>, with <span class="math inline">\epsilon\sim N(0,\sigma^{2})</span>. We keep considering the principal to be risk neutral while the agent’s utility function is CARA represented by a negative exponential utility function <span class="math inline">u(w,e)=-e^{-\eta\left[w-\psi(e)\right]}</span>, with <span class="math inline">\psi(e)=\frac{1}{2}ce^{2}</span>. Therefore, the principal only cares about the expected cost of motivating the agent to accept the contract and exert effort and not about risk sharing.</p>
<p>In these models, the contract follows a linear form such as <span class="math inline">w=t+sx</span> where <span class="math inline">t</span> is a fix component and <span class="math inline">s</span> is the performance-related component.</p>
<p>The problem for the principal is then:</p>
<p><span class="math display"> \underset{e,t,s}{\max}\mathbb{E}\left[x-w\right] </span></p>
<p>subject to:</p>
<p><span class="math display"> \mathbb{E}\left[u(w,e)\right]\geq u(\overline{w},e) </span></p>
<p>as the agent’s participation constraint where <span class="math inline">\overline{w}</span> denotes the minimum acceptable certain monetary equivalent , and</p>
<p><span class="math display"> e\in\arg\max\mathbb{E}\left[u(w,\tilde{e})\right] </span></p>
<p>as the agent’s incentive compatibility constraint.</p>
<section id="solving-optimal-contract-1" class="level2">
<h2 class="anchored" data-anchor-id="solving-optimal-contract-1">Solving optimal contract</h2>
<p>As <span class="math inline">\mathbb{E}\left[e^{k\epsilon}\right]=e^{k^{2}\frac{\sigma^{2}}{2}}</span> for any <span class="math inline">k</span>, the expected agent’s utility is</p>
<p><span class="math display"> \mathbb{E}\left[u(w,e)\right] =-e^{-\eta\left[t+se-\frac{1}{2}ce^{2}-s^{2}\eta\frac{\sigma^{2}}{2}\right]}.</span></p>
<p>Now we can reformulate the agent’s problem as</p>
<p><span class="math display">
a\in\arg\max\hat{w}(a)=t+sa-\frac{1}{2}ca^{2}-s^{2}\eta\frac{\sigma^{2}}{2}
</span></p>
<p>obtaining <span class="math inline">a^*=\frac{s}{c}</span>. So for any given performance incentive s, the principal knows the effort choice of the agent. Introducing this condition into the principal problem reduces the optimization variables (now only the contract terms) and the number of restrictions. By solving the principal model, we obtain the optimal contract:</p>
<p><span class="math display">
\begin{align*}
s^{*} &amp;= \frac{1}{\left[1+c\eta\sigma^{2}\right]}\\
t^{*} &amp;= \overline{w}-\frac{1-c\eta\sigma^{2}}{2c\left[1+c\eta\sigma^{2}\right]^{2}}
\end{align*}
</span></p>
<p>so the variable compensation is high when the cost of effort <span class="math inline">c</span> is low, the degree of risk aversion <span class="math inline">\eta</span> is low, and randomness of the output <span class="math inline">\sigma</span> is low.</p>
<div id="79a078e1" class="cell" data-execution_count="1">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>c<span class="op">=</span><span class="fl">0.8</span> <span class="co"># cost of effort</span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>eta<span class="op">=</span><span class="fl">1.5</span> <span class="co"># risk aversion</span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>w<span class="op">=</span><span class="dv">1</span>     <span class="co"># reservation utility</span></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot s,t,and total, for different values of sigma </span></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>sigma <span class="op">=</span> np.linspace(<span class="dv">0</span>,<span class="dv">2</span>,<span class="dv">10</span>)</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>s <span class="op">=</span> <span class="dv">1</span><span class="op">/</span>(<span class="dv">1</span><span class="op">+</span>c<span class="op">*</span>eta<span class="op">*</span>sigma<span class="op">**</span><span class="dv">2</span>)</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>t <span class="op">=</span> w <span class="op">-</span> (<span class="dv">1</span><span class="op">-</span>c<span class="op">*</span>eta<span class="op">*</span>sigma<span class="op">**</span><span class="dv">2</span>)<span class="op">/</span>(<span class="dv">2</span><span class="op">*</span>c<span class="op">*</span>(<span class="dv">1</span><span class="op">+</span>c<span class="op">*</span>eta<span class="op">*</span>sigma<span class="op">**</span><span class="dv">2</span>)<span class="op">**</span><span class="dv">2</span>) </span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>total <span class="op">=</span> t <span class="op">+</span> s </span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a>effort <span class="op">=</span> s<span class="op">/</span>c </span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a>plt.plot(sigma, s, label<span class="op">=</span><span class="st">'s'</span>)</span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a>plt.plot(sigma, t, label<span class="op">=</span><span class="st">'t'</span>)</span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a>plt.plot(sigma, total, label<span class="op">=</span><span class="st">'total'</span>)</span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a>plt.plot(sigma, effort, label<span class="op">=</span><span class="st">'effort'</span>, linestyle<span class="op">=</span><span class="st">'dashed'</span>)</span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a>plt.legend()</span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a><span class="co"># render sigma symbol in the x label</span></span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">'Value of $\sigma$'</span>)</span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">'Value'</span>)</span>
<span id="cb1-20"><a href="#cb1-20" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">'Optimal contract terms'</span>)</span>
<span id="cb1-21"><a href="#cb1-21" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="mora_hazard_files/figure-html/cell-2-output-1.png" width="589" height="449" class="figure-img"></p>
</figure>
</div>
</div>
</div>
<div id="1fc1cac5" class="cell" data-execution_count="2">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co"># plot the utility of the agent and principal for different values of sigma</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>u_agent <span class="op">=</span> <span class="op">-</span>np.exp(<span class="op">-</span>eta<span class="op">*</span>(t<span class="op">+</span>s<span class="op">*</span>effort<span class="op">-</span><span class="fl">0.5</span><span class="op">*</span>c<span class="op">*</span>effort<span class="op">**</span><span class="dv">2</span><span class="op">-</span>s<span class="op">**</span><span class="dv">2</span><span class="op">*</span>eta<span class="op">*</span>sigma<span class="op">**</span><span class="dv">2</span><span class="op">/</span><span class="dv">2</span>)) </span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>u_principal <span class="op">=</span> effort<span class="op">-</span>t<span class="op">-</span>s<span class="op">*</span>effort</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>plt.plot(sigma, u_agent, label<span class="op">=</span><span class="st">'Agent'</span>)</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>plt.plot(sigma, u_principal, label<span class="op">=</span><span class="st">'Principal'</span>)</span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>plt.legend()</span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">'Value of $\sigma$'</span>)</span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">'Utility'</span>)</span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">'Agent and Principal utility'</span>)</span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="mora_hazard_files/figure-html/cell-3-output-1.png" width="600" height="449" class="figure-img"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="accounting-perfomance-measures" class="level2">
<h2 class="anchored" data-anchor-id="accounting-perfomance-measures">Accounting Perfomance Measures</h2>
<p>Let’s again assume again that <span class="math inline">x</span> and <span class="math inline">y</span> are both accounting signals, such as <span class="math inline">x=e+\epsilon_x</span> and <span class="math inline">y=2e+\epsilon_y</span>, where <span class="math inline">\epsilon_x</span> and <span class="math inline">\epsilon_y</span> are joinly normally distributed with zero means. Then, the joint distribution function <span class="math inline">f(x,y;e)</span> is a bivariate normal distribution with</p>
<ul>
<li><p>Mean vector: <span class="math display">
\mu_{x,y} = \left(\begin{array}{c} e \\ 2e \end{array}\right)
</span></p></li>
<li><p>Covariance matrix: <span class="math display">
\Sigma_{x,y} = \left(\begin{array}{cc} \sigma_x^2 &amp; \rho \sigma_x \sigma_y \\ \rho \sigma_x \sigma_y &amp; \sigma_y^2 \end{array}\right)
</span></p></li>
</ul>
<p>where <span class="math inline">\sigma_x^2</span> is the variance of <span class="math inline">\epsilon_x</span>, <span class="math inline">\sigma_y^2</span> is the variance of <span class="math inline">\epsilon_y</span>, and <span class="math inline">\rho</span> is the correlation coefficient between <span class="math inline">\epsilon_x</span> and <span class="math inline">\epsilon_y</span>. The <a href="#eq-optimal_weights_2" class="quarto-xref">Equation&nbsp;6</a> becomes</p>
<p><span class="math display">
\frac{\beta_x}{\beta_y} = \frac{1-2\frac{\rho \sigma_x \sigma_y}{\sigma_y^2}}{\sigma_x^2}\frac{\sigma_y^2}{2-\frac{\rho \sigma_x \sigma_y}{\sigma_x^2}}
</span></p>
<p>Let’s see the comparative statics of the optimal weights for different values of <span class="math inline">\rho</span> and <span class="math inline">\sigma_y</span>. First, let’s assume that both signals have the same noise, <span class="math inline">\sigma_x=\sigma_y=2.5</span>.</p>
<div id="8794125f" class="cell" data-execution_count="3">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co"># plot the beta_x/beta_y for different values of rho </span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>rho <span class="op">=</span> np.linspace(<span class="op">-</span><span class="dv">1</span>,<span class="dv">1</span>,<span class="dv">20</span>)</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>sigma_y <span class="op">=</span> <span class="fl">2.5</span></span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>sigma_x <span class="op">=</span> <span class="fl">2.5</span></span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a><span class="co"># subplot for rho</span></span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>beta_rho <span class="op">=</span> (<span class="dv">1</span><span class="op">-</span><span class="dv">2</span><span class="op">*</span>(rho<span class="op">*</span>sigma_x<span class="op">*</span>sigma_y)<span class="op">/</span>(sigma_y)<span class="op">**</span><span class="dv">2</span>)<span class="op">/</span>(sigma_x<span class="op">**</span><span class="dv">2</span>)<span class="op">*</span>(sigma_y<span class="op">**</span><span class="dv">2</span>)<span class="op">/</span>(<span class="dv">2</span><span class="op">-</span>(rho<span class="op">*</span>sigma_x<span class="op">*</span>sigma_y)<span class="op">/</span>(sigma_x)<span class="op">**</span><span class="dv">2</span>)</span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a>plt.plot(rho, beta_rho)</span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">'correlation coefficient'</span>)</span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a><span class="co"># add vertical line in x=0</span></span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a>plt.axvline(x<span class="op">=</span><span class="dv">0</span>, color<span class="op">=</span><span class="st">'r'</span>, linestyle<span class="op">=</span><span class="st">'--'</span>)</span>
<span id="cb3-11"><a href="#cb3-11" aria-hidden="true" tabindex="-1"></a><span class="co">## add subtitle</span></span>
<span id="cb3-12"><a href="#cb3-12" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">'Relative Optimal Weights'</span>)</span>
<span id="cb3-13"><a href="#cb3-13" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="mora_hazard_files/figure-html/cell-4-output-1.png" width="590" height="449" class="figure-img"></p>
</figure>
</div>
</div>
</div>
<p>so, if <span class="math inline">\rho=0</span>, the optimal contract weight for <span class="math inline">x</span> is half of the weight for <span class="math inline">y</span>, as this second signal is more sensitive to effort and has the same noise. If <span class="math inline">\rho=-1</span>, then both both signal have full positive weight in the contract. If <span class="math inline">\rho=1</span>, then the signals are substracted from each other in the contract to remove the common noise.</p>
<p>Now, let’s see the comparative statics for different values of <span class="math inline">\sigma_y</span>, considering <span class="math inline">\rho=0</span> and <span class="math inline">\sigma_x=2.5</span>.</p>
<div id="5ea2c038" class="cell" data-execution_count="4">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="co"># plot the beta_x/beta_y for different values of sigma_y</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>rho<span class="op">=</span><span class="dv">0</span></span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>sigma_y <span class="op">=</span> np.linspace(<span class="fl">0.1</span>,<span class="dv">5</span>,<span class="dv">10</span>)</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>sigma_x <span class="op">=</span> <span class="fl">2.5</span></span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a><span class="co"># plot for sigma_y</span></span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a>beta_sigma_y <span class="op">=</span> (<span class="dv">1</span><span class="op">-</span><span class="dv">2</span><span class="op">*</span>(rho<span class="op">*</span>sigma_x<span class="op">*</span>sigma_y)<span class="op">/</span>(sigma_y)<span class="op">**</span><span class="dv">2</span>)<span class="op">/</span>(sigma_x<span class="op">**</span><span class="dv">2</span>)<span class="op">*</span>(sigma_y<span class="op">**</span><span class="dv">2</span>)<span class="op">/</span>(<span class="dv">2</span><span class="op">-</span>(rho<span class="op">*</span>sigma_x<span class="op">*</span>sigma_y)<span class="op">/</span>(sigma_x)<span class="op">**</span><span class="dv">2</span>)</span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a>plt.axvline(x<span class="op">=</span><span class="fl">2.5</span>, color<span class="op">=</span><span class="st">'r'</span>, linestyle<span class="op">=</span><span class="st">'--'</span>)</span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a>plt.plot(sigma_y, beta_sigma_y)</span>
<span id="cb4-9"><a href="#cb4-9" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">'Value of $\sigma_y$'</span>)</span>
<span id="cb4-10"><a href="#cb4-10" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">'Relative Optimal Weights'</span>)</span>
<span id="cb4-11"><a href="#cb4-11" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="mora_hazard_files/figure-html/cell-5-output-1.png" width="579" height="453" class="figure-img"></p>
</figure>
</div>
</div>
</div>
<p>Here the red line the same situation than in the previous plot, meaning that when both signals have the same noise, the optimal weight for <span class="math inline">x</span> is half of the weight for $y. If <span class="math inline">\sigma_y</span> gets closer to zero, then the weight for <span class="math inline">x</span> decreases as <span class="math inline">y</span> gets better signal-to-noise ratio.</p>
</section>
<section id="optimal-contract-with-performance-measures" class="level2">
<h2 class="anchored" data-anchor-id="optimal-contract-with-performance-measures">Optimal contract with Performance Measures</h2>
</section>
<section id="recent-papers-in-accounting" class="level2">
<h2 class="anchored" data-anchor-id="recent-papers-in-accounting">Recent papers in Accounting</h2>
<ul>
<li><p><a href="https://link.springer.com/article/10.1007/s11142-015-9339-6#Sec3">Earnings vs.&nbsp;stock-price based incentives in managerial compensation contracts</a></p></li>
<li><p><a href="https://link.springer.com/article/10.1007/s11142-009-9095-6">Dynamic performance measurement with intangible assets</a></p></li>
<li><p><a href="https://www.nowpublishers.com/article/Details/ACC-007">Dynamic performance measurement</a></p></li>
<li><p><a href="https://www.nowpublishers.com/article/Details/ACC-063">Timeliness, Accuracy, and Relevance in Dynamic Incentive Contracts</a></p></li>
</ul>
</section>
</section>
<section id="multiple-action-models" class="level1">
<h1>Multiple-action models</h1>
<p>This section borrows from <span class="citation" data-cites="Lambert_2001">Lambert (<a href="#ref-Lambert_2001" role="doc-biblioref">2001</a>)</span> Chapter 3 and <span class="citation" data-cites="Bolton_Dewatripont_2005">Bolton and Dewatripont (<a href="#ref-Bolton_Dewatripont_2005" role="doc-biblioref">2005</a>)</span> Chapter 6.</p>
</section>
<section id="disclosure-of-private-information" class="level1">
<h1>Disclosure of Private information</h1>
<p>This section borrows from <span class="citation" data-cites="Lambert_2001">Lambert (<a href="#ref-Lambert_2001" role="doc-biblioref">2001</a>)</span> Chapter 4 and <span class="citation" data-cites="Bolton_Dewatripont_2005">Bolton and Dewatripont (<a href="#ref-Bolton_Dewatripont_2005" role="doc-biblioref">2005</a>)</span> Chapter 5.</p>



</section>


<div id="quarto-appendix" class="default"><section class="quarto-appendix-contents" role="doc-bibliography" id="quarto-bibliography"><h2 class="anchored quarto-appendix-heading">References</h2><div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" role="list">
<div id="ref-Banker_1989" class="csl-entry" role="listitem">
Banker, Rajiv D., and Srikant M. Datar. 1989. <span>“Sensitivity, Precision, and Linear Aggregation of Signals for Performance Evaluation.”</span> <em>Journal of Accounting Research</em> 27 (1): 21–39. <a href="http://www.jstor.org/stable/2491205">http://www.jstor.org/stable/2491205</a>.
</div>
<div id="ref-Bolton_Dewatripont_2005" class="csl-entry" role="listitem">
Bolton, Patrick, and M. Dewatripont. 2005. <em>Contract Theory</em>. Cambridge, Mass: MIT Press.
</div>
<div id="ref-Holmstrom_1979" class="csl-entry" role="listitem">
Holmström, Bengt. 1979. <span>“Moral Hazard and Observability.”</span> <em>The Bell Journal of Economics</em> 10 (1): 74–91. <a href="http://www.jstor.org/stable/3003320">http://www.jstor.org/stable/3003320</a>.
</div>
<div id="ref-Lambert_2001" class="csl-entry" role="listitem">
Lambert, Richard A. 2001. <span>“Contracting Theory and Accounting.”</span> <em>Journal of Accounting and Economics</em> 32 (1–3): 3–87. <a href="https://doi.org/10.1016/S0165-4101(01)00037-4">https://doi.org/10.1016/S0165-4101(01)00037-4</a>.
</div>
<div id="ref-Milgrom_1981" class="csl-entry" role="listitem">
Milgrom, Paul R. 1981. <span>“Good News and Bad News: Representation Theorems and Applications.”</span> <em>The Bell Journal of Economics</em> 12 (2): 380–91. <a href="http://www.jstor.org/stable/3003562">http://www.jstor.org/stable/3003562</a>.
</div>
<div id="ref-Mirrlees_1974" class="csl-entry" role="listitem">
Mirrlees, James A. 1974. <span>“<span class="nocase">Notes on Welfare Economics, Information, and Uncertainty</span>.”</span> In <em><span class="nocase">Welfare, Incentives, and Taxation</span></em>. Oxford University Press. <a href="https://doi.org/10.1093/acprof:oso/9780198295211.003.0003">https://doi.org/10.1093/acprof:oso/9780198295211.003.0003</a>.
</div>
</div></section><section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes"><h2 class="anchored quarto-appendix-heading">Footnotes</h2>

<ol>
<li id="fn1"><p>Additionally, if the agent has bargaining power, they could negotiate up to 161 for high effort. Analyse the Edgeworth box representation.<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section></div></main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>